CREATE TABLE ACCESS_MAPPING_CHANNEL (
CHANNEL varchar(32) NOT NULL ,
FUNCTIONS json DEFAULT NULL ,
LOGIN_ACTIVE int4 DEFAULT '1' ,
PRIMARY KEY (CHANNEL)
 );



-- employee_profile_db.ACCESS_MAPPING_TYPE definition

CREATE TABLE ACCESS_MAPPING_TYPE (
TYPE varchar(32)NOT NULL ,
FUNCTIONS json DEFAULT NULL ,
LOGIN_ACTIVE int4 DEFAULT '1' ,
PRIMARY KEY (TYPE)
);

-- employee_profile_db.APPROVAL_PERMISSION definition

CREATE TABLE APPROVAL_PERMISSION (
APPL_BRANCH_ID varchar(255)NOT NULL,
EMPLOYEE_ID varchar(16)NOT NULL,
AUTH_LEVEL varchar(10)NOT NULL,
PRIMARY KEY (APPL_BRANCH_ID,EMPLOYEE_ID)
) ;

-- employee_profile_db.BRANCH definition

CREATE TABLE BRANCH (
BRANCH_ID varchar(4) DEFAULT NULL,
NAME_EN varchar(100) DEFAULT NULL,
NAME_TH varchar(100) DEFAULT NULL,
REGION_CODE varchar(2) DEFAULT NULL,
CHANNEL_TYPE varchar(1) DEFAULT NULL,
IS_BOOKING_BRANCH int4 NOT NULL,
OWN_BRANCH_ONLY int4 NOT null,
PRIMARY KEY (BRANCH_ID)
);

-- employee_profile_db.EMPLOYEE definition

CREATE TABLE EMPLOYEE (
EMPLOYEE_ID varchar(16)NOT NULL ,
FIRSTNAME_EN varchar(100)DEFAULT NULL,
LASTNAME_EN varchar(100)DEFAULT NULL,
FIRSTNAME_TH varchar(100)DEFAULT NULL,
LASTNAME_TH varchar(100)DEFAULT NULL,
LICENSE_ID varchar(30)DEFAULT NULL,
OC_CODE varchar(6)DEFAULT NULL,
OC_NAME varchar(256)DEFAULT NULL,
OC_NAME_TH varchar(256)DEFAULT NULL,
EMAIL varchar(100)DEFAULT NULL,
POSITION_NAME varchar(100)DEFAULT NULL,
SAM_EMPLOYEE_ID varchar(6)DEFAULT NULL,
SAM_FIRSTNAME_EN varchar(100)DEFAULT NULL,
SAM_LASTNAME_EN varchar(100)DEFAULT NULL,
SAM_FIRSTNAME_TH varchar(100)DEFAULT NULL,
SAM_LASTNAME_TH varchar(100)DEFAULT NULL,
SAM_OC_CODE varchar(16)DEFAULT NULL,
SAM_OC_NAME varchar(256)DEFAULT NULL,
SAM_OC_NAME_TH varchar(256)DEFAULT NULL,
SAM_EMAIL varchar(100)DEFAULT NULL,
PRIMARY KEY (EMPLOYEE_ID)
);

-- indidb2_0.GENERAL_PARAM definition

CREATE TABLE GENERAL_PARAM (
TYPE varchar(25) NOT NULL,
VALUE json DEFAULT NULL,
SERVER_ONLY char(1) DEFAULT NULL,
PRIMARY KEY (TYPE)
) ;

-- employee_profile_db.LOGIN_BRANCH definition

CREATE TABLE LOGIN_BRANCH (
BRANCH_ID varchar(4)NOT NULL,
EMPLOYEE_ID varchar(16)NOT NULL,
APPL_BRANCH_ID varchar(255)NOT NULL,
ROLES json DEFAULT NULL,
PRIMARY KEY (BRANCH_ID,EMPLOYEE_ID)
) ;

-- employee_profile_db.LOGIN_BRANCH definition

CREATE TABLE LOGIN_BRANCH (
  BRANCH_ID varchar(4) NOT NULL,
  EMPLOYEE_ID varchar(16) NOT NULL,
  APPL_BRANCH_ID varchar(255) NOT NULL,
  ROLES json DEFAULT NULL,
  PRIMARY KEY (BRANCH_ID,EMPLOYEE_ID)
);

-- employee_profile_db.LOGIN_SESSION definition

CREATE TABLE LOGIN_SESSION (
EMPLOYEE_ID varchar(16) NOT NULL,
LAST_ACTIVITY_TIME timestamp NOT NULL,
DEVICE_ID varchar(45) NOT NULL,
STATUS varchar(45) NOT NULL,
APP_NAME varchar(45) NOT NULL,
TOKEN varchar(400) DEFAULT NULL,
PRIMARY KEY (EMPLOYEE_ID)
) ;

-- employee_profile_db.ORGANIZATION definition

CREATE TABLE ORGANIZATION (
OC_CODE varchar(6)NOT NULL,
OC_NAME_TH varchar(256)NOT NULL,
OC_NAME_EN varchar(256)NOT NULL,
PRIMARY KEY (OC_CODE)
) ;
